---
title: "AMP-AD Manuscript Analyses"
output: html_notebook
---

Create the qq plot.
```{r}
AMPAD::qqplotFigure()
```

Pull targeted genesets

```{r}
targetedGeneSets <- AMPAD::collateEnrichmentSets()
str(targetedGeneSets)
```

For each of the three build the data frame of the respective Analyses

```{r}
targetedEnrichment <- list()
targetedEnrichment$ad <- AMPAD::run_amp_ad_enrichment(targetedGeneSets$ad,
                                                      'AD',
                                                      hgnc = TRUE,
                                                      manifestId = 'syn11870970')

targetedEnrichment$cell <- AMPAD::run_amp_ad_enrichment(targetedGeneSets$cell,
                                                        'Cell',
                                                        hgnc= TRUE,
                                                        manifestId = 'syn11870970')

targetedEnrichment$deg <- AMPAD::run_amp_ad_enrichment(targetedGeneSets$deg,
                                                       'DEG',
                                                       hgnc=FALSE,
                                                       manifestId = 'syn11870970')


```


Add adjusted p-values 

```{r}
targetedEnrichment$ad$adj.pval <- p.adjust(targetedEnrichment$ad$fisherPval,method='fdr')
targetedEnrichment$deg$adj.pval <- p.adjust(targetedEnrichment$deg$fisherPval,method='fdr')
targetedEnrichment$cell$adj.pval <- p.adjust(targetedEnrichment$cell$fisherPval,method='fdr')
```

Make cell type summary plots

x- axis : module
y- axis fisher-'s odds ratio

```{r}
modMeta <- AMPAD::getModuleMetainfo('syn11870970')
dummyDf <- dplyr::filter(targetedEnrichment$cell,adj.pval<=0.05)
dummyDf <- dplyr::left_join(dummyDf,modMeta)
dummyDf$ModuleBrainRegion <- factor(dummyDf$ModuleBrainRegion,levels = unique(dummyDf$ModuleBrainRegion))

g <- ggplot2::ggplot(dummyDf,
                     ggplot2::aes(x = Module,
                                  y = fisherOR,
                                  fill = category))
g <- g+ggplot2::geom_col(position = 'dodge')
g <- g + ggplot2::scale_y_log10()
g <- g + ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1))
g <- g + ggplot2::coord_flip()

g

```

AD genetics summary


```{r}
dummyDf <- dplyr::filter(targetedEnrichment$ad,adj.pval<=0.05)
dummyDf <- dplyr::left_join(dummyDf,modMeta)
dummyDf$ModuleBrainRegion <- factor(dummyDf$ModuleBrainRegion,levels = unique(dummyDf$ModuleBrainRegion))

g <- ggplot2::ggplot(dummyDf,
                     ggplot2::aes(x = Module,
                                  y = fisherOR,
                                  fill = category))
g <- g+ggplot2::geom_col(position = 'dodge')
g <- g + ggplot2::scale_y_log10()
g <- g + ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1))
g <- g + ggplot2::coord_flip()

g


```


Reformate DEG results for visualization

```{r}
tcx_keep <- intersect(grep('TCX',targetedEnrichment$deg$ModuleNameFull),
                      grep('TCX',targetedEnrichment$deg$category))
phg_keep <- intersect(grep('PHG',targetedEnrichment$deg$ModuleNameFull),
                      grep('PHG',targetedEnrichment$deg$category))
cbe_keep <- intersect(grep('CBE',targetedEnrichment$deg$ModuleNameFull),
                      grep('CBE',targetedEnrichment$deg$category))
dlpfc_keep <- intersect(grep('DLPFC',targetedEnrichment$deg$ModuleNameFull),
                      grep('DLPFC',targetedEnrichment$deg$category))
stg_keep <- intersect(grep('STG',targetedEnrichment$deg$ModuleNameFull),
                      grep('STG',targetedEnrichment$deg$category))
ifg_keep <- intersect(grep('IFG',targetedEnrichment$deg$ModuleNameFull),
                      grep('IFG',targetedEnrichment$deg$category))
fp_keep <- intersect(grep('FP',targetedEnrichment$deg$ModuleNameFull),
                      grep('FP',targetedEnrichment$deg$category))
deg <- targetedEnrichment$deg[c(tcx_keep,phg_keep,cbe_keep,dlpfc_keep,stg_keep,ifg_keep,fp_keep),]
deg$adj.pval <- p.adjust(deg$fisherPval,method='fdr')
deg <- dplyr::filter(deg,adj.pval<=0.05)
dumfun <- function(x){
  y<-grep('UP',x)
  y2 <- grep('DOWN',x)
  z <- x
  z[y] <- 'Up'
  z[y2] <- 'Down'
  return(z)
}
sexfun <- function(x){
  y<-grep('\\.FEMALE',x)
  y2 <- grep('\\.MALE',x)
  z <- rep('All',length(x))
  z[y] <- 'Female'
  z[y2] <- 'Male'
  return(z)
}
deg <- dplyr::mutate(deg,direction = dumfun(category))
deg <- dplyr::mutate(deg,sex = sexfun(category))
deg <- dplyr::mutate(deg,dirbysex = paste0(direction,'.',sex))
deg <- dplyr::left_join(deg,modMeta)
```
Plot DEG results

```{r}
g <- ggplot2::ggplot(deg,ggplot2::aes(x = Module,
                                      y = fisherOR,
                                      fill = direction))
g <- g + ggplot2::geom_col(position = 'dodge')
g <- g + ggplot2::facet_grid(. ~ sex)
g <- g + ggplot2::scale_y_log10()
g <- g + ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1))
g <- g + ggplot2::coord_flip()
g

```
